//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestaurant_db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurant_dbContext : DbContext
    {
        public restaurant_dbContext()
            : base("name=restaurant_dbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dish> dish { get; set; }
        public DbSet<ingredients> ingredients { get; set; }
        public DbSet<recipes> recipes { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
