//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestaurant_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class dish
    {
        public dish()
        {
            this.recipes = new HashSet<recipes>();
        }
    
        public int id_dish { get; set; }
        public string dish_name { get; set; }
        public int dish_price { get; set; }
    
        public virtual ICollection<recipes> recipes { get; set; }
    }
}
