//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestaurant_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        public recipes()
        {
            this.ingredients = new HashSet<ingredients>();
        }
    
        public int id_recipe { get; set; }
        public string recipe { get; set; }
        public int dish_id { get; set; }
    
        public virtual dish dish { get; set; }
        public virtual ICollection<ingredients> ingredients { get; set; }
    }
}
